# Mock REST API Server Configuration

server:
  port: 9009

mockrest:
  file-server:
    remoteHost: 10.46.1.165
    username: nutanix
    password: "nutanix/4u"
    remoteFilePath: "/home/nutanix/data/farhan"
    download-directory: "/tmp/downloaded_files"
    upload-directory: "/home/nutanix/data/farhan/uploads/"
    upload-url: "http://10.46.1.165/farhan/uploads/"

